#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-push checks..."
echo "Running ESLint..."
npm run lint
echo "Running tests..."
npm run test -- --watch=false --browsers=ChromeHeadless
echo "Running build..."
npm run build -- --configuration production
echo "Pre-push checks passed!"
